import { v4 as uuidv4 } from "uuid";

export const templates = [
  {
    id: uuidv4(),
    name: "HĐCN Quyền sử dụng đất toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-quyen-su-dung-dat-toan-bo",
    templateId: 5,
  },
  {
    id: uuidv4(),
    name: "HĐCN Quyền sử dụng đất một phần (đồng sử dụng).docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-quyen-su-dung-dat-mot-phan-de-dong-su-dung",
    templateId: 4,
  },
  {
    id: uuidv4(),
    name: "HĐCN Quyền sử dụng đất một phần (để sở hữu toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-quyen-su-dung-dat-mot-phan-de-su-dung-toan-bo",
    templateId: 4,
  },
  {
    id: uuidv4(),
    name: "HĐCN Quyền sử dụng đất nông nghiệp toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-quyen-su-dung-dat-nong-nghiep-toan-bo",
    templateId: 5,
  },
  {
    id: uuidv4(),
    name: "HĐCN một phần đất và TSGLVD (để đồng sử dụng).docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-mot-phan-dat-va-tsglvd-de-dong-su-dung",
    templateId: 6,
  },
  {
    id: uuidv4(),
    name: "HĐCN một phần đất và TSGLVD (để sử dụng toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-mot-phan-dat-va-tsglvd-de-su-dung-toan-bo",
    templateId: 6,
  },
  {
    id: uuidv4(),
    name: "HĐCN đất và tài sản gắn liền với đất toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdcn-dat-va-tsglvd-toan-bo",
    templateId: 7,
  },
  {
    id: uuidv4(),
    name: "HĐMB căn hộ toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-can-ho-toan-bo",
    templateId: 1,
  },
  {
    id: uuidv4(),
    name: "HĐMB căn hộ một phần (để sở hữu toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-can-ho-mot-phan-so-huu-toan-bo",
    templateId: 1,
  },
  {
    id: uuidv4(),
    name: "HĐMB nhà đất toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-nha-dat-toan-bo",
    templateId: 54,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho căn hộ toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-can-ho-toan-bo",
    templateId: 62,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho căn hộ một phần (đồng sử dụng).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-can-ho-mot-phan-de-dong-su-dung",
    templateId: 121,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho căn hộ một phần (sử dụng toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-can-ho-mot-phan-de-su-dung-toan-bo",
    templateId: 121,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho đất nông nghiệp toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-dat-nong-nghiep-toan-bo",
    templateId: 11,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho đất toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-dat-toan-bo",
    templateId: 11,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho đất một phần (đồng sử dụng).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-dat-mot-phan-de-dong-su-dung",
    templateId: 10,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho đất một phần (để sử dụng toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-dat-mot-phan-de-su-dung-toan-bo",
    templateId: 10,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho nhà đất toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-nha-dat-toan-bo",
    templateId: 15,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho nhà đất một phần (đồng sử dụng).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-nha-dat-mot-phan-de-dong-su-dung",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "HĐ tặng cho nhà đất một phần (sử dụng toàn bộ).docx",
    type: "agreement",
    subCategory: "nhom-tang-cho",
    path: "hd-tang-cho-nha-dat-mot-phan-de-su-dung-toan-bo",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "Uỷ quyền toàn bộ quyền sử dụng đất.docx",
    type: "agreement",
    subCategory: "nhom-uy-quyen",
    path: "uy-quyen-toan-bo-quyen-su-dung-dat",
    templateId: 30,
  },
  {
    id: uuidv4(),
    name: "Uỷ quyền toàn bộ nhà + đất.docx",
    type: "agreement",
    subCategory: "nhom-uy-quyen",
    path: "uy-quyen-toan-bo-nha-dat",
    templateId: 30,
  },
  {
    id: uuidv4(),
    name: "Uỷ quyền căn hộ toàn bộ.docx",
    type: "agreement",
    subCategory: "nhom-uy-quyen",
    path: "uy-quyen-toan-bo-can-ho",
    templateId: 30,
  },
  {
    id: uuidv4(),
    name: "HĐMB xe ôtô.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-xe-oto",
    templateId: 2,
  },
  {
    id: uuidv4(),
    name: "HĐMB xe máy.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-xe-may",
    templateId: 79,
  },
  {
    id: uuidv4(),
    name: "HĐMB xe ôtô + Biển số xe.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-xe-oto-bien-so-xe",
    templateId: 2,
  },
  {
    id: uuidv4(),
    name: "Uỷ quyền xe ôtô.docx",
    type: "agreement",
    subCategory: "nhom-uy-quyen",
    path: "uy-quyen-xe-oto",
    templateId: 30,
  },
  {
    id: uuidv4(),
    name: "HĐMB tài sản.docx",
    type: "agreement",
    subCategory: "nhom-chuyen-nhuong-mua-ban",
    path: "hdmb-tai-san",
    templateId: 3,
  },
  {
    id: uuidv4(),
    name: "VB huỷ.docx",
    type: "agreement",
    subCategory: "nhom-huy-sua-doi",
    path: "vb-huy",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "VB chấm dứt hợp đồng.docx",
    type: "agreement",
    subCategory: "nhom-huy-sua-doi",
    path: "vb-cham-dut-hd",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "VB chấm dứt hợp đồng uỷ quyền.docx",
    type: "agreement",
    subCategory: "nhom-huy-sua-doi",
    path: "vb-cham-dut-hq-uy-quyen",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "HĐ đặt cọc.docx",
    type: "agreement",
    subCategory: "nhom-thue-muon-dat-coc",
    path: "hd-dat-coc",
    templateId: 0,
  },
  {
    id: uuidv4(),
    name: "HĐ đặt cọc chưa xoá chấp.docx",
    type: "agreement",
    subCategory: "nhom-thue-muon-dat-coc",
    path: "hd-dat-coc-chua-xoa-chap",
    templateId: 0,
  },
];
