export const extractAddress = (address: string) => {
  const addressArray = address.split(",");
  const reversedAddressArray = addressArray.reverse();

  return {
    thành_phố: reversedAddressArray[0]?.trim() || null,
    phường: reversedAddressArray[1]?.trim() || null,
    thôn: reversedAddressArray[2]?.trim() || null,
  };
};

const CHI_NHANH_VAN_PHONG_DANG_KY_DAT: Record<string, string> = {
  "hoàn kiếm": "Hoàn Kiếm",
  "cửa nam": "Hoàn Kiếm",
  "ba đình": "Ba Đình",
  "ngọc hà": "Ba Đình",
  "giảng võ": "Ba Đình",
  "hai bà trưng": "Hai Bà Trưng",
  "vĩnh tuy": "Hai Bà Trưng",
  "bạch mai": "Hai Bà Trưng",
  "đống đa": "Đống Đa",
  "kim liên": "Đống Đa",
  "văn miếu – quốc tử giám": "Đống Đa",
  láng: "Đống Đa",
  "ô chợ dừa": "Đống Đa",
  "hồng hà": "Hoàng Mai",
  "lĩnh nam": "Hoàng Mai",
  "hoàng mai": "Hoàng Mai",
  "vĩnh hưng": "Hoàng Mai",
  "tương mai": "Hoàng Mai",
  "định công": "Hoàng Mai",
  "hoàng liệt": "Hoàng Mai",
  "yên sở": "Hoàng Mai",
  "thanh xuân": "Thanh Xuân",
  "khương đình": "Thanh Xuân",
  "phương liệt": "Thanh Xuân",
  "cầu giấy": "Cầu Giấy",
  "nghĩa đô": "Cầu Giấy",
  "yên hòa": "Cầu Giấy",
  "tây hồ": "Tây Hồ",
  "phú thượng": "Tây Hồ",
  "tây tựu": "Bắc Từ Liêm",
  "phú diễn": "Bắc Từ Liêm",
  "xuân đỉnh": "Bắc Từ Liêm",
  "đông ngạc": "Bắc Từ Liêm",
  "thượng cát": "Bắc Từ Liêm",
  "từ liêm": "Nam Từ Liêm",
  "xuân phương": "Nam Từ Liêm",
  "tây mỗ": "Nam Từ Liêm",
  "đại mỗ": "Nam Từ Liêm",
  "long biên": "Long Biên",
  "bồ đề": "Long Biên",
  "việt hưng": "Long Biên",
  "phúc lợi": "Long Biên",
  "hà đông": "Hà Đông",
  "dương nội": "Hà Đông",
  "yên nghĩa": "Hà Đông",
  "phú lương": "Hà Đông",
  "kiến hưng": "Hà Đông",
  "thanh liệt": "Thanh Trì",
  "chương mỹ": "Chương Mỹ",
  "sơn tây": "Sơn Tây",
  "tùng thiện": "Sơn Tây",
  "thanh trì": "Thanh Trì",
  "đại thanh": "Thanh Trì",
  "nam phù": "Thanh Trì",
  "ngọc hồi": "Thanh Trì",
  "thượng phúc": "Thường Tín",
  "thường tín": "Thường Tín",
  "chương dương": "Thường Tín",
  "hồng vân": "Thường Tín",
  "phú xuyên": "Phú Xuyên",
  "phượng dực": "Phú Xuyên",
  "chuyên mỹ": "Phú Xuyên",
  "đại xuyên": "Phú Xuyên",
  "thanh oai": "Thanh Oai",
  "bình minh": "Thanh Oai",
  "tam hưng": "Thanh Oai",
  "dân hòa": "Thanh Oai",
  "vân đình": "Ứng Hòa",
  "ứng thiên": "Ứng Hòa",
  "hòa xá": "Ứng Hòa",
  "ứng hòa": "Ứng Hòa",
  "mỹ đức": "Mỹ Đức",
  "hồng sơn": "Mỹ Đức",
  "phúc sơn": "Mỹ Đức",
  "hương sơn": "Mỹ Đức",
  "phú nghĩa": "Chương Mỹ",
  "xuân mai": "Chương Mỹ",
  "trần phú": "Chương Mỹ",
  "hòa phú": "Chương Mỹ",
  "quảng bị": "Chương Mỹ",
  "minh châu": "Ba Vì",
  "quảng oai": "Ba Vì",
  "vật lại": "Ba Vì",
  "cổ đô": "Ba Vì",
  "bất bạt": "Ba Vì",
  "suối hai": "Ba Vì",
  "ba vì": "Ba Vì",
  "yên bài": "Ba Vì",
  "đoài phương": "Sơn Tây",
  "phúc thọ": "Phúc Thọ",
  "phúc lộc": "Phúc Thọ",
  "hát môn": "Phúc Thọ",
  "thạch thất": "Thạch Thất",
  "hạ bằng": "Thạch Thất",
  "tây phương": "Thạch Thất",
  "hòa lạc": "Thạch Thất",
  "yên xuân": "Quốc Oai",
  "quốc oai": "Quốc Oai",
  "hưng đạo": "Quốc Oai",
  "kiều phú": "Quốc Oai",
  "phù cát": "Quốc Oai",
  "hoài đức": "Hoài Đức",
  "dương hòa": "Hoài Đức",
  "sơn đồng": "Hoài Đức",
  "an khánh": "Hoài Đức",
  "đan phượng": "Đan Phượng",
  "ô diên": "Đan Phượng",
  "liên minh": "Đan Phượng",
  "gia lâm": "Gia Lâm",
  "thuận an": "Gia Lâm",
  "bát tràng": "Gia Lâm",
  "phù đổng": "Gia Lâm",
  "thư lâm": "Đông Anh",
  "đông anh": "Đông Anh",
  "phúc thịnh": "Đông Anh",
  "thiên lộc": "Đông Anh",
  "vĩnh thanh": "Đông Anh",
  "mê linh": "Mê Linh",
  "yên lãng": "Mê Linh",
  "tiến thắng": "Mê Linh",
  "quang minh": "Mê Linh",
  "sóc sơn": "Sóc Sơn",
  "đa phúc": "Sóc Sơn",
  "nội bài": "Sóc Sơn",
  "trung giã": "Sóc Sơn",
  "kim anh": "Sóc Sơn",
};

export const getChiNhanhVanPhongDangKyDat = (phường: string | null) => {
  if (!phường) {
    return "";
  }

  const normalizedPhuong = phường
    .toLowerCase()
    .replace("phường", "")
    .replace("xã", "")
    .trim();

  const chiNhanhVanPhongDangKyDat =
    CHI_NHANH_VAN_PHONG_DANG_KY_DAT[normalizedPhuong];

  return chiNhanhVanPhongDangKyDat || "";
};
